name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: docudio

    runs-on: ubuntu-latest
    steps:
      - name: "deploy"
        uses: abinmn/gcp-storage-bucket-action@v1.0
        with:
          # GCP service key encoded as base64. The account associated with the key should have permissions to make changes in storage bucket.
          service_key: ${{secrets.gcpsecret}}
          # The folder you want to deploy. Default is the repository. You can change this value if you have a build step and point this to that build folder.
         # Bucket name
          bucket_name: "creosmnias"
          # Name of the project that contains the storage bucket.
          project: "sturdy-tenure-294803"
          # Path of your homepage in cloud storage bucket.
          home_page_path: "Creosomnias.html"
          # Path of the 404 page to be shown
          error_page_path: "Creosomnias.html"
