- name: GCP Cloud Storage: Deploy
  # You may pin to the exact commit or the version.
  # uses: abinmn/gcp-storage-bucket-action@db210e26048a30d98e1095b372b3b02b29432e65
  uses: abinmn/gcp-storage-bucket-action@v1.0
  with:
    # GCP service key encoded as base64. The account associated with the key should have permissions to make changes in storage bucket.
    service_key: ${{secret.gcpsecret}}
    # The folder you want to deploy. Default is the repository. You can change this value if you have a build step and point this to that build folder.
    build_folder: 
    # Bucket name
    bucket_name: "creosmnias"
    # Name of the project that contains the storage bucket.
    project: "My FIrst Project"
    # Path of your homepage in cloud storage bucket.
    home_page_path: "Creosomnias.html"
    # Path of the 404 page to be shown
    error_page_path: "Creosomnias.html"
